add Dominion
btelle/alexa-boardgame-answers pull request #1
Opened 2017-02-04 04:23 UTC by gamershwang

updated Sources
updated game names
updated equipment types
updated sample utterances to include ‘we’
added dominion json file

2017-02-04 04:25 UTC, gamershwang commented
I'm new to this...I hope I added everything correctly

2017-02-04 08:30 UTC, btelle requested changes
Overall this looks good, left a comment on sample utterances. Fix that and it should be good to go

2017-02-04 08:30 UTC, btelle commented on alexa/sample_utterances.txt
> +StartingEquipmentInGame how much {Type} do we get in {Game}
This file shouldn't have duplicate entries, one per question phrasing works

2017-02-04 23:49 UTC, merged

2017-02-04 23:54 UTC, btelle commented
Hey, I merged this in. I just added some test cases for it and fixed a couple of syntax problems in the file in the master branch. I'll add some docs on creating tests if you're interested in contributing more. Thanks for the PR!

2017-02-05 05:23 UTC, gamershwang commented
Sweet sounds good. I'll definitely keep at it, thanks for putting this up! 

I just saw your post on hackster too, so I'll try to do some testing on my own before the next PR. As I said I'm just getting started using github, AWS, and the skills kit so I really appreciate you putting up the documentation and such, it's been a great guide.